### ISSUE TITLE
The name 'GridLayout' does not exist in the current context	

### ISSUE THREAD

**Issue by fangwancong** [syncfusion/maui-demos#12]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'GridLayout' does not exist in the current context	SampleBrowser.Maui.Core (net6.0), SampleBrowser.Maui.Core (net6.0-android), SampleBrowser.Maui.Core (net6.0-ios), SampleBrowser.Maui.Core (net6.0-maccatalyst), SampleBrowser.Maui.Core (net6.0-windows10.0.19041)	D:\Personal\GitHub\MAUI\maui-demos\SampleBrowser.Maui.Core\Extensions\SampleView.cs	308	Active

on VS2022 17.2.0 Preview 1.0 , Windows 11.

**Comment by PaulAnderson02** [comment]
Hi @fangwancong ,

Greetings from Syncfusion. The issue has been now resolved and now supports .NET MAUI preview 13.
