### ISSUE TITLE
Syncfusion SchedulerAppointment endless loop after setting Value to Notes

### ISSUE THREAD

**Issue by TiMeJuMp** [syncfusion/maui-demos#17]
I figured an issue on the Note property in SchedulerAppointment. 
After setting a Value to Note there will be an Endless loop because not the private property is set to value.  
Therefore everytime again the Set-Part is called again and again
![image](https://user-images.githubusercontent.com/6890804/157080841-e131f3ed-daa9-4bcc-b274-20950e8eed9b.png)

**Comment by saiganesh-sakthivel** [comment]
Hi @TiMeJuMp ,

**#Regarding SchedulerAppointment endless loop after setting Value to Notes**
We have already found and fixed the reported scenario from our end. We will include the issue fix in our upcoming weekly nuget release which is expected to roll out on March 15, 2022. We will let you know once the release is rolled out. If you need a patch for the reported issue fix before the weekly nuget, we will provide to you.

Regards, 
SaiGanesh Sakthivel
