### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')

### ISSUE THREAD

**Issue by mbiesiad** [syncfusion/maui-demos#34]
# Description / Current behavior:
`Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')` occurs for site `https://www.syncfusion.com/maui-controls/decoder-challenge`

# Expected behavior
No mentioned error (handled error).

# Steps to replicate
1. Go to: https://www.syncfusion.com/maui-controls/decoder-challenge
2. Check DevTools Console
3. See `Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')`

# Additional information
Browser: Brave
OS: Windows 10
For Firefox and Chrome works fine - doesn't occur.

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/200669260-a90c4fbe-6dab-4643-bf9e-a46bbca72786.png)

Best wishes,

**Comment by RubaShanmugamm** [comment]
We are not clear with your exact requirement, could you please provide more details regarding the reported issue to proceed further on this?
